---

- hosts: localhost
  connection: local
  tasks:

    - name: "Find our running Windows host"
      ec2_remote_facts:
        region: "{{ target_region }}"
        profile: "{{ windows_profile }}"
        filters:
          "tag:Experiment": "{{ experiment_name }}"
          "tag:Env": "{{ target_env }}"
          "tag:Name": "{{ windows_instance_host_name }}"
          "tag:Role": "{{ windows_instance_role_tag }}"
          "instance-state-name": "running"
      register: smb_host_facts

    - name: Get the Administrator password if you want to RDP in
      ec2_win_password:
        region: "{{ target_region }}"
        profile: "{{ windows_profile }}"
        key_file: "{{ aws_ssh_key_file }}"
        instance_id: "{{ smb_host_facts.instances[0].id }}"
      register: win_pwd

    - name: Print out the Administrator password (not a good practice)
      debug:
        var: win_pwd
